"use client";
import { FC, ReactNode, useState, useCallback } from "react";
import AppNav from "./components/NavBar/AppNav";
import Footer from "./components/Footer/Footer";
import type { Metadata } from "next";
import AuthProvider from "./context/auth/AuthProvider";
import ExitPopUp from "./components/PopUpModal/ExitPopup";

export const metadata: Metadata = {
  title: "ScholarlyHelp",
  description: "Generated by create next app",
};

interface MainLayoutProps {
  children: ReactNode;
}

const MainLayout: FC<MainLayoutProps> = ({ children }) => {
  const [openExitPopup, setOpenExitPopup] = useState<boolean>(false);
  const [userInteracted, setUserInteracted] = useState<boolean>(false);

  const handleUserInteraction = useCallback(() => {
    if (!userInteracted) setUserInteracted(true);
  }, [userInteracted]);

  const handleMouseLeave = (event: React.MouseEvent<HTMLDivElement>) => {
    if (event.clientY <= 0 && !userInteracted) {
      setOpenExitPopup(true);
    }
  };

  return (
    <AuthProvider>
      <div
        onClick={handleUserInteraction}
        onInput={handleUserInteraction}
        onMouseLeave={handleMouseLeave}
      >
        <AppNav />
        {children}
        <Footer />
        <ExitPopUp
          open={openExitPopup}
          handleClose={() => setOpenExitPopup(false)}
        />
      </div>
    </AuthProvider>
  );
};

export default MainLayout;
