"use client";
import { FC, ReactNode } from "react";
import AppNav from "./components/NavBar/AppNav";
import Footer from "./components/Footer/Footer";
import type { Metadata } from "next";
import AuthProvider from "./context/auth/AuthProvider";

export const metadata: Metadata = {
  title: "ScholarlyHelp",
  description: "Generated by create next app",
};
interface MainLayoutProps {
  children: ReactNode;
}
const MainLayout: FC<MainLayoutProps> = ({ children }) => {
  return (
    <AuthProvider>
      <AppNav />
      {children}
      <Footer />
    </AuthProvider>
  );
};
export default MainLayout;
